# This workflow will run tests using node and then publish
# a package to NPM Packages when a release is created.
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: create-wordpress-project
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci && node ./scripts/setup-test.js
      - uses: actions/upload-artifact@v2
        with:
          name: test-project-folder
          path: ./__test-project__

  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: create-wordpress-project

      - uses: actions/download-artifact@v2
        with:
          name: test-project-folder

      - name: Determine composer cache directory
        shell: bash
        run: "echo \"COMPOSER_CACHE_DIR=$(composer config cache-dir)\" >> $GITHUB_ENV"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - uses: php-actions/composer@v5
        with:
          php_version: 7.3

      - name: PHPCS
        uses: chekalsky/phpcs-action@v1
        with:
          phpcs_bin_path: ./vendor/bin/phpcs

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: create-wordpress-project

      - uses: actions/download-artifact@v2
        with:
          name: test-project-folder

      - uses: php-actions/composer@v5
        with:
          php_version: 7.3

      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        env:
          REQUIRE_DEV: true
        with:
          args: analyse

  lint:
    name: ESLint & Stylelint
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: create-wordpress-project

      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - uses: actions/download-artifact@v2
        with:
          name: test-project-folder

      - run: npm ci && npm run lint
